### ISSUE TITLE
数组下标越界src/library/binlog.go

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#1]
func (h *binlogHandler) OnRow(e *canal.RowsEvent) error

原因：
开始的日志点t1，在服务器启动前，数据库对表foo做了DDL操作，这样服务器启动后获取到的row结构跟日志开始处t1已经不相同。

**Comment by jilieryuyi** [comment]
已经修复

**Comment by mia0x75** [comment]
CREATE TABLE `t1` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`value` VARCHAR(25) NOT NULL
);

# 测试AFTER
ALTER TABLE t1 ADD `length` DECIMAL(9,2) AFTER `id`;

也就是字段顺序变了，而且类型也变了，新表
t1 (
`id`
`length`
`value`
)

**Comment by mia0x75** [comment]
这是一个暂时无法完美解决的问题，目前已经不崩溃了，关闭。
