### ISSUE TITLE
build.sh脚本错误

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#12]
cp -rf ${current_path}/src/config/* ${current_path}/bin/config/

=>

cp -rf ${current_path}/src/config/ ${current_path}/bin/config/

**Comment by jilieryuyi** [comment]
这个是正确的，你说的这个mac下面这个运行没有问题，linux下面最终目录会变成 /config/config/这种形式，可以试试~

**Comment by mia0x75** [comment]
我就在Linux下，会提示目标目录不存在问题，你之前是有判断，然后建目录的，改了之后的没有这个判断。

**Comment by jilieryuyi** [comment]
已调整
