### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#14]
INFO[2017-12-04 11:45:42] create BinlogSyncer with config {3017243 mariadb 172.30.17.250 3306 replicate   gbk false false <nil> false 0 30s 0s} 
INFO[2017-12-04 11:45:42] websocket服务-等待新的连接...
INFO[2017-12-04 11:45:42] binlog调试： mysql-bin.000072 221909292
INFO[2017-12-04 11:45:42] websocket服务-监听: 0.0.0.0:9997
INFO[2017-12-04 11:45:42] skip dump, use last binlog replication pos (mysql-bin.000072, 221909292) or GTID %!s(<nil>) 
[martini] listening on 0.0.0.0:9997 (development)
INFO[2017-12-04 11:45:42] begin to sync binlog from position (mysql-bin.000072, 221909292) 
INFO[2017-12-04 11:45:42] register slave for master server a.b.c.d:3306 
INFO[2017-12-04 11:45:42] tcp服务-等待新的连接...
INFO[2017-12-04 11:45:42] start sync binlog at binlog file (mysql-bin.000072, 221909292) 
INFO[2017-12-04 11:45:42] rotate to (mysql-bin.000072, 221909292)
INFO[2017-12-04 11:45:42] rotate binlog to (mysql-bin.000072, 221909292) 
INFO[2017-12-04 11:45:42] binlog发送广播： %lms.tb_riskmanage_idempotence_control{"database":"lms"uuid":"bb81abc4eef3452281df1e490a825e33","timestamp":"2017-11-27 10:44:44"},"event_type":"insert","time":1512359142},"event_index":5821,"table":"tb_riskmanage_idempotence_control"} 
INFO[2017-12-04 11:45:42] http服务-发送广播
INFO[2017-12-04 11:45:42] kafka服务-发送消息
INFO[2017-12-04 11:45:42] 37 -- [108 109 115 46 116 98 95 114 105 115 107 109 97 110 97 103 101 95 105 100 101 109 112 111 116 101 110 99 101 95 99 111 110 116 114 111 108] -- [123 34 100 97 116 97 98 97 115 101 34 58 34 108 109 115 34 117 117 105 100 34 58 34 98 98 56 49 97 98 99 52 101 101 102 51 52 53 50 50 56 49 100 102 49 101 52 57 48 97 56 50 53 101 51 51 34 44 34 116 105 109 101 115 116 97 109 112 34 58 34 50 48 49 55 45 49 49 45 50 55 32 49 48 58 52 52 58 52 52 34 125 44 34 101 118 101 110 116 95 116 121 112 101 34 58 34 105 110 115 101 114 116 34 44 34 116 105 109 101 34 58 49 53 49 50 51 53 57 49 52 50 125 44 34 101 118 101 110 116 95 105 110 100 101 120 34 58 53 56 50 49 44 34 116 97 98 108 101 34 58 34 116 98 95 114 105 115 107 109 97 110 97 103 101 95 105 100 101 109 112 111 116 101 110 99 101 95 99 111 110 116 114 111 108 34 125] 
INFO[2017-12-04 11:45:42] binlog发送广播： decision.tb_lb_decision_grade{"database":"decision"id":22755401,"apply_code":"00511711278249","dimension":"稳定性","seq":9,"name":"本地居住年限","value":"��60个月","score":39,"last_update_time":"2017-11-27 10:44:44"},"event_type":"insert","time":1512359142},"event_index":5852,"table":"tb_lb_decision_grade"} 
INFO[2017-12-04 11:45:42] tcp服务-广播
INFO[2017-12-04 11:45:42] tcp服务-没有连接的客户端
INFO[2017-12-04 11:45:42] http服务-发送广播
INFO[2017-12-04 11:45:42] kafka服务-发送消息
INFO[2017-12-04 11:45:42] binlog发送广播： decision.tb_lb_decision_grade{"database":"decision"id":22755414,"apply_code":"00511711278249","dimension":"车辆特征","seq":22,"name":"评估价","value":"＞5万，≤10万","score":12,"last_update_time":"2017-11-27 10:44:44"},"event_type":"insert","time":1512359142},"event_index":5865,"table":"tb_lb_decision_grade"} 
INFO[2017-12-04 11:45:42] http服务-发送广播
INFO[2017-12-04 11:45:42] kafka服务-发送消息
INFO[2017-12-04 11:45:42] binlog发送广播： ++_.+b__y__+-g{"da+aba_e":"++_"ID":11647087,"USERNAME":"+i+_+i1","OPDATE":"2017-11-27 10:45:30","MODULECODE":"特批业务","OPCONTENT":"提前结清申请","OPSIGN":"保存成功!","OPSQL":"","OPIP":"112.103.18.174","HOSTMAC":""},"e+e++_+y-e":"i+_e_+","+i+e":1512359142},"e+e++_i+de|":5866,"+ab+e":"+b__y__+-g"} 
INFO[2017-12-04 11:45:42] +c-服务-广播
INFO[2017-12-04 11:45:42] +c-服务-没有连接的客户端
INFO[2017-12-04 11:45:42] h++-服务-发送广播
INFO[2017-12-04 11:45:42] +af+a服务-发送消息
INFO[2017-12-04 11:45:42] bi++-g发送广播： #++_.+b_c-++_ac+_ide+--+e+ce_c-++_-+{"da+aba_e":"++_"++id":"220eaa4b-981a-4092-aa8d-e198cacbc921","+i+e_+a+-":"2017-11-27 10:44:45"},"e+e++_+y-e":"i+_e_+","+i+e":1512359142},"e+e++_i+de|":5867,"+ab+e":"+b_c-++_ac+_ide+--+e+ce_c-++_-+"} 
INFO[2017-12-04 11:45:42] +c-服务-广播
ESC[36mINFOESC[0m[2017-12-04 11:56:00] binlog发送广播： ^]^@decision.tb_lb_decision_grade{"database":"decision"id":24464933,"apply_code":"2941171204238","dimension":"稳定性","seq":9,"name":"本
地居住年限","value":"<U+FEFF>＞60个月","score":39,"last_update_time":"2017-12-04 11:55:07"},"event_type":"delete","time":1512359760},"event_index":739,"table":"tb_lb_decision_grade"}

**Comment by mia0x75** [comment]
INFO[2017-12-04 12:49:34] +c-服务-广播                                     
INFO[2017-12-04 12:49:34] +c-服务-没有连接的客户端                               
INFO[2017-12-04 12:49:34] h++-服务-发送广播                                  
INFO[2017-12-04 12:49:34] +af+a服务-发送消息                                 
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：COMP_TYPE %!_(<+i+>)            
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：ZIP %!_(<+i+>)                  
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：PROPERTY %!_(<+i+>)             
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：WEBSITE %!_(<+i+>)              
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：FAX %!_(<+i+>)                  
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：PRI_BUSINESS %!_(<+i+>)         
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：EMP_NUMS %!_(<+i+>)             
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：LICENCE %!_(<+i+>)              
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：WORK_PHONE1 %!_(<+i+>)          
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：WORK_PHONE2 %!_(<+i+>)          
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：WORK_PHONE3 %!_(<+i+>)          
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：WORK_PHONE4 %!_(<+i+>)          
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：DEPT_NAME %!_(<+i+>)            
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：CATEGORY %!_(<+i+>)             
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：HIGH_RISK %!_(<+i+>)            
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：ON_DUTY_DT %!_(<+i+>)           
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：LEAVE_DUTY_DT %!_(<+i+>)        
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：PAY_TERM %!_(<+i+>)             
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：SOCIAL_CARD %!_(<+i+>)          
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：CPF %!_(<+i+>)                  
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：ON_DUTY %!_(<+i+>)              
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：c-+_e+ai+ %!_(<+i+>)            
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：yy_+ %!_(<+i+>)                 
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：--e_a+i+g_+i+e %!_(<+i+>)       
WARN[2017-12-04 12:49:34] bi++-g不支持的类型：i__-_-d+c+_c-+-a+y %!_(<+i+>)   
INFO[2017-12-04 12:49:34] bi++-g发送广播：

**Comment by mia0x75** [comment]
开始几条正确，然后很快就乱码了。

```
INFO[2017-12-07 19:44:08] tcp服务-没有连接的客户端                               
[[326507 422111 <nil> 2927 郑书林 <nil> 2017-12-04 17:21:22 <nil> zhengshulin <nil> 01] [326507 422111 2017-12-04 00:00:00 2927 郑书林 [] 2017-12-04 17:21:22 2017-12-04 17:24:29 zhengshulin zhengshulin 01]]
INFO[2017-12-07 19:44:08] tcp服务-广播：db.table1{"database":"lms","event":{"data":{"old_data":{"ID":326507,"APPLYID":422111,"MSTIME":NULL,"SALESMAN":"2927","SALESMAN_STR":"郑书林","MTQKSM":NULL,"CREATEDATE":"2017-12-04 17:21:22","UPDATEDATE":NULL,"CREATEBY":"zhengshulin","UPDATEBY":NULL,"DATASTATE":"01"},"new_data":{"ID":326507,"APPLYID":422111,"MSTIME":"2017-12-04 00:00:00","SALESMAN":"2927","SALESMAN_STR":"郑书林","MTQKSM":"","CREATEDATE":"2017-12-04 17:21:22","UPDATEDATE":"2017-12-04 17:24:29","CREATEBY":"zhengshulin","UPDATEBY":"zhengshulin","DATASTATE":"01"}},"event_type":"update","time":1512647048},"event_index":22,"table":"table1"} 
INFO[2017-12-07 19:44:08] tcp服务-没有连接的客户端                               
[[391984 重庆随缘饭店  <nil>  <nil>   <nil> <nil> <nil> <nil> <nil> <nil> 2018-02-20 00:00:00 <nil> 7 0 350 12123 <nil> <nil> <nil> <nil> 422111 <nil> <nil>  <nil> <nil> <nil> 1  <nil> <nil>  2  <nil> 1 2026-04-23 00:00:00 <nil>   <nil> 0 <nil> <nil> <nil>     <nil> 1 2 0    <nil> <nil> <nil>  <nil>]]
INFO[2017-12-07 19:44:08] tcp服务-广播：++_.+b_+b_+cdc{"da+aba_e":"++_","e+e++":{"da+a":{"ID":391984,"CORPNAME":"重庆随缘饭店","FAREN":"","REGDATE":NULL,"GDXX":"","NSXX":NULL,"YWYC":"","CBDW":"","CBJS":NULL,"YLYE":NULL,"YBYE":NULL,"BDWCBDATE":NULL,"BEGINCBDAE":NULL,"YWZD":NULL,"XSZLASTDATE":"2018-02-20 00:00:00","JZZLASETDATE":NULL,"WZCS":7.00,"WZKF":0.00,"WZJE":350.00,"WZYY":"12123","BXBEGINDATE":NULL,"BXENDDATE":NULL,"DKFS":NULL,"HKFS":NULL,"APPLYID":422111,"ZCZJ":NULL,"JZZ":NULL,"KHJBQK":"","FEERATE":NULL,"DEAL_DATE":NULL,"DEAL_PEOPLE":NULL,"SXZ":"1","+h+b-+dhf|":"","GJJJFDW":NULL,"GJJSTATUS":NULL,"GJJREMARK":"","RFAJSTATUS":2,"RFAJREMARK":"","FCCXJL":NULL,"JSZ":"1","JSZLASTDATE":"2026-04-23 00:00:00","--i+i-+":NULL,"cb_f+ag":"","g++_f+ag":"","cb_e+d_da+e":NULL,"b+_i_+ic_f+ag":"0","e|-e_ie+ce_yea__":NULL,"-a_++e__f+ag":NULL,"-a_++e__+++":NULL,"c+_+_c-_deg_ee":"","-+he__h-+_e_f+ag":"","-+he__h-+_e_add_":"","c_edi+ca_d_f+ag":"","i+_+_a+ce__e+a_+":NULL,"b_ea+__++e_fa+g":"1","b_ea+__++e_dea+_+y-e":"2","b+c++e_++e++e_--i++__+i+e":0,"-_-+ide_add_e___-_--f_f+ag":"","+-_+gage_ca__-ay_f+ag":"","+e|+_day_+-_+gage_f+ag":"","e|ec++e_++de_+yi+g":NULL,"_egi_+e__+a+_+i+_+i+e":NULL,"-+e__+a+_+i+_f+ag":NULL,"-+++i+e_--+icy__e_+_ic+i-+":"","-+e__+a+_+i+_-_-+e_f+ag":NULL},"e+e++_+y-e":"i+_e_+","+i+e":1512647048},"e+e++_i+de|":23,"+ab+e":"+b_+b_+cdc"} 
INFO[2017-12-07 19:44:08] +c-服务-没有连接的客户端
```

**Comment by mia0x75** [comment]
![screenshot from 2017-12-08 14-23-35](https://user-images.githubusercontent.com/5111356/33754348-c7d259a2-dc26-11e7-88e5-1fa760d05331.png)

会不会跟这个打印的信息有关

**Comment by jilieryuyi** [comment]
跟这个没有关，这个是封包的时候，前缀有两个字节表示的表名称长度
