### ISSUE TITLE
Websocket客户端断线，尝试重新连接

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#2]
1. 服务端启动
2. 浏览器端启动
3. 连接成功后，关闭服务器，模拟服务崩溃
4. 服务器重新上线

观察一段时间浏览器console

2017-12-02 08:23:12 心跳返回值： ok 
client.js:42:2
2017-12-02 08:23:14 客户端断线，尝试重新连接 
client.js:42:2
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
client.js:60
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
client.js:60
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
client.js:60
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
client.js:60
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
client.js:60
2017-12-02 08:23:14 设置注册分组返回值： ok 
client.js:42:2
2017-12-02 08:23:15 心跳返回值： ok 

一次会有多个InvalidStateError

**Comment by jilieryuyi** [comment]
这个是重连机制问题，做了一个优化，已经提交
