### ISSUE TITLE
DROP TABLE后cache没有处理

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#20]
Step 1: 创建表：
```
CREATE TABLE dt_bool (dt_bit bit);
```

Step 2: 添加行：
```
INSERT INTO dt_bool VALUES (0);
```

Step 3: 收到信息：
```
2017-12-06 08:44:51 9次收到事件：{"database":"drafts","event":{"data":{"dt_bit":0},"event_type":"insert","time":1512521091},"event_index":16,"table":"dt_bool"}
```

Step 4: 删除重建表：
```
DROP TABLE dt_bool;
CREATE TABLE dt_bool (c BOOL);
```

Step 5: 添加行：
```
INSERT INTO dt_bool VALUES (1);
```

Step 6: 收到信息：
2017-12-06 08:44:53 10次收到事件：{"database":"drafts","event":{"data":{"dt_bit":1},"event_type":"insert","time":1512521093},"event_index":17,"table":"dt_bool"}

问题：注意收到的信息中的列名依然是dt_bit，应该是c。
解决：处理CREATE TABLE/DROP TABLE事件。

**Comment by jilieryuyi** [comment]
go-mysql bug，已修复

**Comment by mia0x75** [comment]
想到另外一个case，没有测试，因为看代码只是增加了DROP TABLE匹配，所以RENAME估计也会有相同问题。

Step 1: create table t1 (c INT);
Step 2: insert into t1 VALUES (1);
Step 3: rename table t1 to t2;
Step 4: create table t1 (d INT);
Step 5: insert into t1 VALUES (2);

**Comment by jilieryuyi** [comment]
rename和alter本身已经支持了

**Comment by mia0x75** [comment]
RENAME不行，已经验证了。

{"database":"drafts","event":{"data":{"c":99999999999},"event_type":"insert","time":1512717680},"event_index":711,"table":"t1"}

应该是{"d":99999999999}，RENAME后没有清除缓存，新建的同名表字段已变。

**Comment by jilieryuyi** [comment]
RENAME  go-mysql这个库有bug，已经提交给作者了
