### ISSUE TITLE
INT(3)类型，报binlog未知的行

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#21]
&{Name:interview_process Type:1 Collation: RawType:int(3) IsAuto:false IsUnsigned:false EnumValues:[] SetValues:[]}

也有可能根schema变更有关，我再确认。

**Comment by jilieryuyi** [comment]
&{Name:c Type:1 Collation: RawType:int(3) IsAuto:false IsUnsigned:false EnumValues:[] SetValues:[]},===,int32, == 3 
test.dt_int8{"database":"test","event":{"data":{"c":3},"event_type":"insert","time":1512689044},"event_index":324,"table":"dt_int8"}
这个可以的，应该是别的问题
