### ISSUE TITLE
JSON编码问题

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#26]
字段类型：
`name` varchar(100) CHARACTER SET gbk DEFAULT NULL,

输出：
"name":"\ufffd\ufffd11\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd佱\ufffd\ufffd\ufffd\ufffd\ufffd\ufffdŬ\ufffd\ufffd\ufffd\ufffd\ufffdҶ\ufffd֪\ufffd\ufffd\ufffd\ufffd"

真实值：
【11月社区颁奖】你的努力，我都知道！ 

Step 1:
CREATE TABLE `ut_gbk` (
  `name` varchar(100) CHARACTER SET gbk DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

Step 2:
insert into ut_gbk values ('【11月社区颁奖】你的努力，我都知道！');

**Comment by jilieryuyi** [comment]
暂时不支持其他的编码，go默认是utf8的，非utf8会有问题

**Comment by mia0x75** [comment]
"golang.org/x/text/encoding/charmap" 这个包里面的方法不知道能否处理。

**Comment by jilieryuyi** [comment]
目前已修改为统一使用官方json编码~
