### ISSUE TITLE
binlgo服务-SaveBinlogPostionCache缓冲区满

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#27]
好像执行一个稍大的SQL文件，就会出现，不管有没有tcp连接。（允许了tcp/http）

WARN[2017-12-09 17:58:13] binlgo服务-SaveBinlogPostionCache缓冲区满...       
WARN[2017-12-09 17:58:13] binlgo服务-SaveBinlogPostionCache缓冲区满...       
WARN[2017-12-09 17:58:13] binlgo服务-SaveBinlogPostionCache缓冲区满...       
WARN[2017-12-09 17:58:13] binlgo服务-SaveBinlogPostionCache缓冲区满...       
WARN[2017-12-09 17:58:13] binlgo服务-SaveBinlogPostionCache缓冲区满...       
WARN[2017-12-09 17:58:13] binlgo服务-SaveBinlogPostionCache缓冲区满...       
WARN[2017-12-09 17:58:13] binlgo服务-SaveBinlogPostionCache缓冲区满...       
WARN[2017-12-09 17:58:13] binlgo服务-SaveBinlogPostionCache缓冲区满...

**Comment by jilieryuyi** [comment]
已优化
