### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#29]
panic: runtime error: slice bounds out of range

goroutine 41 [running]:
library/binlog.(*binlogHandler).getPoint(0xc42006e1f8, 0xc42703520d, 0x6, 0x3, 0x3, 0xc420171000)
        /home/mxu/Projects/src/github.com/jilieryuyi/wing-binlog-go/src/library/binlog/handler.go:35 +0x13f
library/binlog.(*binlogHandler).append(0xc42006e1f8, 0xc423ff3a18, 0x90b3a0, 0xc4242c8318, 0xc42703d6c0)
        /home/mxu/Projects/src/github.com/jilieryuyi/wing-binlog-go/src/library/binlog/handler.go:115 +0xa65
library/binlog.(*binlogHandler).OnRow(0xc42006e1f8, 0xc42656ba10, 0x3, 0xc426f7df80)
        /home/mxu/Projects/src/github.com/jilieryuyi/wing-binlog-go/src/library/binlog/handler.go:229 +0x22ee
github.com/siddontang/go-mysql/canal.(*Canal).handleRowsEvent(0xc420096dd0, 0xc423f92ff0, 0x10, 0xc407bad2b3)
        /home/mxu/Projects/src/github.com/jilieryuyi/wing-binlog-go/vendor/src/github.com/siddontang/go-mysql/canal/sync.go:183 +0x216
github.com/siddontang/go-mysql/canal.(*Canal).runSyncBinlog(0xc420096dd0, 0x0, 0x0)
        /home/mxu/Projects/src/github.com/jilieryuyi/wing-binlog-go/vendor/src/github.com/siddontang/go-mysql/canal/sync.go:81 +0x898
github.com/siddontang/go-mysql/canal.(*Canal).run(0xc420096dd0, 0x0, 0x0)
        /home/mxu/Projects/src/github.com/jilieryuyi/wing-binlog-go/vendor/src/github.com/siddontang/go-mysql/canal/canal.go:201 +0x151
github.com/siddontang/go-mysql/canal.(*Canal).Run(0xc420096dd0, 0xc420012a00, 0x10)
        /home/mxu/Projects/src/github.com/jilieryuyi/wing-binlog-go/vendor/src/github.com/siddontang/go-mysql/canal/canal.go:170 +0x2b
github.com/siddontang/go-mysql/canal.(*Canal).RunFrom(0xc420096dd0, 0xc420012a00, 0x10, 0x7b89bd9, 0x0, 0x0)
        /home/mxu/Projects/src/github.com/jilieryuyi/wing-binlog-go/vendor/src/github.com/siddontang/go-mysql/canal/canal.go:178 +0x5d
library/binlog.(*Binlog).Start.func1(0xc42006e1e0)
        /home/mxu/Projects/src/github.com/jilieryuyi/wing-binlog-go/src/library/binlog/binlog.go:111 +0x54
created by library/binlog.(*Binlog).Start
        /home/mxu/Projects/src/github.com/jilieryuyi/wing-binlog-go/src/library/binlog/binlog.go:105 +0x1e5

**Comment by mia0x75** [comment]
&{Name:totalShould Type:2 Collation: RawType:double IsAuto:false IsUnsigned:false EnumValues:[] SetValues:[]},===,float64, == 11647.35

崩溃前一条。


定义的类型：
```
+---------------------+---------------+------+-----+---------+----------------+
| Field               | Type          | Null | Key | Default | Extra          |
+---------------------+---------------+------+-----+---------+----------------+
| id                  | int(11)       | NO   | PRI | NULL    | auto_increment |
| transactionNo       | varchar(100)  | YES  | MUL | NULL    |                |
| returnId            | int(11)       | YES  | MUL | NULL    |                |
| returnDetailId      | int(11)       | YES  |     | NULL    |                |
| custName            | varchar(100)  | YES  |     | NULL    |                |
| contractNo          | varchar(100)  | YES  | MUL | NULL    |                |
| tounaId             | int(11)       | YES  |     | NULL    |                |
| siteName            | varchar(100)  | YES  |     | NULL    |                |
| productName         | varchar(100)  | YES  |     | NULL    |                |
| phases              | int(11)       | YES  |     | NULL    |                |
| shouldReturnDate    | datetime      | YES  |     | NULL    |                |
| totalShould         | double        | YES  |     | NULL    |                |
.
.
.
```

**Comment by jilieryuyi** [comment]
已修复
