### ISSUE TITLE
关于后台进程问题

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#35]
建议有 -d或者--daemon选项，toml配置日志输入位置，有rotate更好。然后直接启动到后台，日志输出到文件。

**Comment by jilieryuyi** [comment]
go 官方目前对守护进程并没有很好的支持，都是一些第三方的实现，需要对跨平台进行比较多的测试才行，之前考虑过，，现在还未实现

**Comment by mia0x75** [comment]
多输出一点信息，还可以吧 ;-)

![screenshot from 2017-12-15 20-18-51](https://user-images.githubusercontent.com/5111356/34042001-a290573e-e1d5-11e7-84e2-b2ebd6166073.png)

**Comment by jilieryuyi** [comment]
👍 赞

**Comment by jilieryuyi** [comment]
linux+unix相关系统已支持守护进程模式 运行时加 -d或者-daemon即可
