### ISSUE TITLE
这几个看是否可以修复，或者给go-mysql提交一个PR

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#38]
正常关闭，不应该有错误提示。

ERRO[2017-12-16 15:36:19] canal start sync binlog err: context canceled
INFO[2017-12-16 15:36:19] wing-binlog-go service exit: context canceled
github.com/siddontang/go-mysql/canal/sync.go:55:
github.com/siddontang/go-mysql/canal/canal.go:203:
ERRO[2017-12-16 15:36:19] connection was bad
ERRO[2017-12-16 15:36:19] close sync with err: Sync was closed

**Comment by jilieryuyi** [comment]
这个错误信息不会影响后面的运行的~
