### ISSUE TITLE
这种权限问题能处理么？

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#39]
用root启动
用普通用户stop

```
$ bin/wing-binlog-go -stop
PANI[2017-12-16 20:25:15] unix服务客户端异常：dial unix .../wing-binlog-go.sock: connect: permission denied 
panic: (*logrus.Entry) (0x871a80,0xc420070960)
.
.
.
```

**Comment by jilieryuyi** [comment]
这种权限问题，系统控制，没办法

**Comment by mia0x75** [comment]
好像主函数加个

defer func() {
		if err := recover(); err != nil {}
	}()

能够不显示堆栈信息，那么我的问题是，到处加这种函数代码会不会很难看。


在有，在init()函数中
app_config, _ := config.GetAppConfig()
是否改成这样更好呢？
app_config, err := config.GetAppConfig()
if err != nil {
  panic(...)
}

**Comment by jilieryuyi** [comment]
显示只是为了定位问题所在，recover是用于异常恢复的，但是现在这个问题是不可恢复的

**Comment by jilieryuyi** [comment]
现在已经去掉了unix实现，统一使用tcp
