### ISSUE TITLE
DROP TABLE支持还有点问题

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#40]
看了正则，应该不能支持 DROP TABLE IF EXISTS t1;

->

```
expDropTable   = regexp.MustCompile("(?i)^DROP\\sTABLE(\\sIF\\sEXISTS){0,1}\\s.*?`{0,1}(.*?)`{0,1}\\.{0,1}`{0,1}([^`\\.]+?)`{0,1}($|\\s)")
```

**Comment by jilieryuyi** [comment]
drop table is exists dt_time;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'is exists dt_time' at line 1

mysql 不支持这样的语句，另外执行的语句都是binlog格式化过的，你这种执行方式，等到获取binlog的时候不一定就长这样的~ 你可以试试， binlog获取到的是这种  drop table dt_time /*注释*/

**Comment by mia0x75** [comment]
drop table is exists dt_time;

drop table IF exists dt_time;

这个不是binlog问题，是正则拿不到正确的表名，无法清除cache。

**Comment by mia0x75** [comment]
Mysql 5.6
![5 6](https://user-images.githubusercontent.com/5111356/34137687-437abf62-e4a7-11e7-90b2-828bb8202995.png)

Mysql 5.7
![5 7](https://user-images.githubusercontent.com/5111356/34137706-4f09a7c6-e4a7-11e7-9ef1-22713e31a59f.png)

**Comment by mia0x75** [comment]
go-mysql PR
