### ISSUE TITLE
数据重发会不会有顺序问题

### ISSUE THREAD

**Issue by mia0x75** [jilieryuyi/wing-binlog-go#41]
在写Web服务器的时候，Web服务器崩溃后，再启动，再从数据库操作，结果先收到id=1025的，后收到id=1024的。

![screenshot from 2017-12-22 15-31-18](https://user-images.githubusercontent.com/5111356/34289463-a0c0069a-e72d-11e7-985a-c94cc337a07c.png)

**Comment by jilieryuyi** [comment]
最新版本的http采用多线程发送，并不能保证按顺序到达~ 每个事件包含一个原子递增的event_index索引，可以以此来实现某些需求！

**Comment by jilieryuyi** [comment]
已移除重发功能
